#ifndef __CONSTS_H__
#define __CONSTS_H__

#define ARTICLE_CNT 16384
#define SAMPLE_CNT 16384
#define WORD_SZE 2048
#define WORD_CNT 1048576
#define PATCH_BUF_SZE 36 * 1024 * 1024

// #define DEBUG_MOST_WORD_PRINT
// #define DEBUG_CATCH_FREQ_1000
// #define DEBUG_PRINT_MOST_FREQS
// #define DEBUG_PRINT_ARTICLE_FEATURE
// #define DEBUG_PRINT_ARTICLE_FINGER
// #define DEBUG_PRINT_SAMPLE_INFO

#endif