#ifndef __CONSTS_H__
#define __CONSTS_H__

#define ARTICLE_CNT 40000
#define SAMPLE_CNT 20000
// #define WORD_SZE 80
#define WORD_CNT 100
#define WORD_CNT_SINGLE 6500
// #define PATCH_BUF_SZE 36 * 1024 * 1024
#define TRIE_NODE_CNT 999999
#define TOTAL_WORD 3000000

// #define DEBUG_MOST_WORD_PRINT
// #define DEBUG_CATCH_FREQ_1000
// #define DEBUG_PRINT_MOST_FREQS
// #define DEBUG_PRINT_ARTICLE_FEATURE
// #define DEBUG_PRINT_ARTICLE_FINGER
// #define DEBUG_PRINT_SAMPLE_INFO
// #define DEBUG_PRINT_ARRAY_APPEND

#endif